apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: copy-secrets-to-ephemeral-cluster
spec:
  image: quay.io/redhat-appstudio/appstudio-utils@sha256:586149e3f18d966f681d956ab074b4e1d8433663d615ed86e19a3804ba952dfe
  params:
    - name: credentials
      type: string
      description: A volume containing credentials to the remote cluster
    - name: kubeconfig
      type: string
      description: Relative path to the kubeconfig in the mounted cluster credentials volume
    - name: namespace
      type: string
      description: The destination namespace for the secrets
    - name: labelSelector
      type: string
      description: A label selector for the secrets to be copied
  env:
    - name: DEST_KUBECONFIG
      value: "/credentials/$(params.kubeconfig)"
    - name: NAMESPACE
      value: "$(params.namespace)"
    - name: LABEL_SELECTOR
      value: "$(params.labelSelector)"
  volumeMounts:
    - name: "$(params.credentials)"
      mountPath: /credentials
  script: |
    #!/bin/bash
    set -eo pipefail

    oc get secrets -l "$LABEL_SELECTOR" -o json \
      | jq ".items[].metadata.namespace=\"$NAMESPACE\"" \
      | jq 'del(.items[] | .metadata.creationTimestamp, .metadata.uid, .metadata.resourceVersion, .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration")' \
      | oc apply --kubeconfig=$DEST_KUBECONFIG -f -
